version: '3.7'

services:
  zoo:
    image: zookeeper:3.5.5
    hostname: zoo
    user: zookeeper
    ports:
      - "1235:1235"
    environment:
      ZOO_MY_ID: 1
  ch:
    image: yandex/clickhouse-server:19.15.2.2
    ports:
      - "1237:1237"
      - "1238:1238"
  tg_proxy:
    image: local_docker_reg:8443/proxy_image
    volumes:
      - ./telegram_proxy/telegram_proxy.key:/telegram_proxy.key
    ports:
      - "1234:1234"
